module.exports={
    status:{
        verified:"VERIFIED",
        unverified:"UNVERIFIED"
    },
    jobStatus:{
        avelable:"AVELABLE",
        expired:"EXPIRED"
    },
    userType:{
        student:"STUDENT",
        admin:"ADMIN",
        compeny:"COMPENY"
    }
}