module.exports={
    status:{
        verified:"VERIFIED",
        unverified:"UNVERIFIED"
    },
    jobStatus:{
        avelable:"AVELABLE",
        expired:"EXPIRED"
    },
    useType:{
        student:"STUDENT",
        admin:"ADMIN"
    }
}